/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'sent' : IDL.Null,
  'received' : IDL.Null,
});
export const CrowdfundingStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'funded' : IDL.Null,
  'failed' : IDL.Null,
});
export const CrowdfundingRewardTier = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'maxBackers' : IDL.Opt(IDL.Nat),
  'backerCount' : IDL.Nat,
  'minPledgeCents' : IDL.Nat,
});
export const CrowdfundingFundingModel = IDL.Variant({
  'allOrNothing' : IDL.Null,
  'keepWhatYouRaise' : IDL.Null,
});
export const CrowdfundingCategory = IDL.Variant({
  'research' : IDL.Null,
  'civic' : IDL.Null,
  'education' : IDL.Null,
  'community' : IDL.Null,
  'crisisResponse' : IDL.Null,
  'humanitarian' : IDL.Null,
  'youth' : IDL.Null,
});
export const CrowdfundingMilestone = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'achievedAt' : IDL.Opt(IDL.Int),
  'bonusFSUAmount' : IDL.Nat,
  'description' : IDL.Text,
  'targetCents' : IDL.Nat,
});
export const CrowdfundingCampaign = IDL.Record({
  'id' : IDL.Text,
  'status' : CrowdfundingStatus,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'rewardTiers' : IDL.Vec(CrowdfundingRewardTier),
  'fundingModel' : CrowdfundingFundingModel,
  'approvedByAdmin' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'deadline' : IDL.Int,
  'tenantId' : IDL.Text,
  'goalCents' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'fsuContributionBps' : IDL.Nat,
  'backerCount' : IDL.Nat,
  'currency' : IDL.Text,
  'totalFSUDistributed' : IDL.Nat,
  'category' : CrowdfundingCategory,
  'raisedCents' : IDL.Nat,
  'milestones' : IDL.Vec(CrowdfundingMilestone),
});
export const CrowdfundingPledge = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'referrerCode' : IDL.Opt(IDL.Text),
  'receiptCode' : IDL.Text,
  'createdAt' : IDL.Int,
  'backer' : IDL.Principal,
  'campaignId' : IDL.Text,
  'amountCents' : IDL.Nat,
  'rewardTierId' : IDL.Opt(IDL.Text),
  'fsuEarned' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VoteChoice = IDL.Variant({
  'no' : IDL.Null,
  'yes' : IDL.Null,
  'abstain' : IDL.Null,
});
export const RankedChoiceEntry = IDL.Record({
  'rank' : IDL.Nat,
  'candidateId' : IDL.Text,
});
export const CampaignType = IDL.Variant({
  'action' : IDL.Null,
  'awareness' : IDL.Null,
  'fundraiser' : IDL.Null,
  'petition' : IDL.Null,
});
export const ProposalType = IDL.Variant({
  'resolution' : IDL.Null,
  'communityInitiative' : IDL.Null,
  'amendment' : IDL.Null,
  'budget' : IDL.Null,
  'policy' : IDL.Null,
});
export const VotingMechanism = IDL.Variant({
  'simpleMajority' : IDL.Null,
  'liquidDelegation' : IDL.Null,
  'supermajority66' : IDL.Null,
  'supermajority75' : IDL.Null,
  'rankedChoice' : IDL.Null,
});
export const RoyaltyPoolType = IDL.Variant({
  'event' : IDL.Null,
  'leadership' : IDL.Null,
  'global' : IDL.Null,
  'finFracFran' : IDL.Null,
});
export const TenantTier = IDL.Variant({
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
  'organization' : IDL.Null,
});
export const ForumCategory = IDL.Variant({
  'resources' : IDL.Null,
  'general' : IDL.Null,
  'regional' : IDL.Null,
  'campaigns' : IDL.Null,
  'activism' : IDL.Null,
  'announcements' : IDL.Null,
});
export const MembershipTierLevel = IDL.Variant({
  'free' : IDL.Null,
  'founder' : IDL.Null,
  'executive' : IDL.Null,
  'affiliate' : IDL.Null,
  'ambassador' : IDL.Null,
  'partner' : IDL.Null,
  'associate' : IDL.Null,
});
export const EarningType = IDL.Variant({
  'eventCommission' : IDL.Null,
  'activityBonus' : IDL.Null,
  'directReferral' : IDL.Null,
  'levelOverride' : IDL.Null,
  'royaltyPool' : IDL.Null,
  'finFracFran' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const CampaignStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : CampaignStatus,
  'title' : IDL.Text,
  'endDate' : IDL.Int,
  'orgId' : IDL.Text,
  'goal' : IDL.Nat,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'supporterCount' : IDL.Nat,
  'campaignType' : CampaignType,
  'startDate' : IDL.Int,
});
export const CommissionRate = IDL.Record({
  'basisPoints' : IDL.Nat,
  'tier' : MembershipTierLevel,
  'flatAmountUnits' : IDL.Nat,
  'isActive' : IDL.Bool,
  'earningType' : EarningType,
  'depthLevel' : IDL.Nat,
});
export const CrowdfundingConfig = IDL.Record({
  'defaultFSUContributionBps' : IDL.Nat,
  'milestoneAchievementBonusBps' : IDL.Nat,
  'creatorFSUBonus' : IDL.Nat,
});
export const TenantStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'suspended' : IDL.Null,
});
export const TenantSubscription = IDL.Record({
  'monthlyCents' : IDL.Nat,
  'tier' : TenantTier,
  'renewalDate' : IDL.Int,
  'startDate' : IDL.Int,
});
export const TenantBranding = IDL.Record({
  'orgName' : IDL.Text,
  'primaryColor' : IDL.Text,
  'logoUrl' : IDL.Text,
  'welcomeMessage' : IDL.Text,
});
export const Tenant = IDL.Record({
  'id' : IDL.Text,
  'status' : TenantStatus,
  'subscription' : IDL.Opt(TenantSubscription),
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberCount' : IDL.Nat,
  'tier' : TenantTier,
  'storageUsedMb' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'branding' : IDL.Opt(TenantBranding),
  'trialEndsAt' : IDL.Opt(IDL.Int),
});
export const FSUPoolStatus = IDL.Record({
  'totalOutstandingFSU' : IDL.Nat,
  'valuePerUnitCents' : IDL.Nat,
  'poolSizeUnits' : IDL.Nat,
  'nextDistributionLabel' : IDL.Text,
});
export const WalletType = IDL.Variant({
  'internetIdentity' : IDL.Null,
  'plug' : IDL.Null,
  'stoic' : IDL.Null,
});
export const Wallet = IDL.Record({
  'linkedAt' : IDL.Int,
  'walletType' : WalletType,
  'address' : IDL.Text,
  'balanceICP' : IDL.Float64,
  'walletLabel' : IDL.Text,
});
export const EarningStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'processing' : IDL.Null,
});
export const EarningRecord = IDL.Record({
  'id' : IDL.Text,
  'member' : IDL.Principal,
  'status' : EarningStatus,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sourceId' : IDL.Text,
  'earningType' : EarningType,
  'amountUnits' : IDL.Nat,
  'depthLevel' : IDL.Nat,
});
export const MemberTierRecord = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'joinedAt' : IDL.Int,
  'tier' : MembershipTierLevel,
  'upgradedAt' : IDL.Int,
  'sponsorPrincipal' : IDL.Opt(IDL.Principal),
  'sponsorCode' : IDL.Opt(IDL.Text),
});
export const Vote = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Nat,
  'voter' : IDL.Principal,
  'delegatedTo' : IDL.Opt(IDL.Principal),
  'castAt' : IDL.Int,
  'choice' : VoteChoice,
  'proposalId' : IDL.Nat,
  'rankedChoices' : IDL.Vec(RankedChoiceEntry),
});
export const DelegationRecord = IDL.Record({
  'delegateTo' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'delegator' : IDL.Principal,
  'proposalId' : IDL.Opt(IDL.Nat),
  'revokedAt' : IDL.Opt(IDL.Int),
});
export const DownlineMember = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'joinedAt' : IDL.Int,
  'tier' : MembershipTierLevel,
  'directReferralCount' : IDL.Nat,
});
export const EarningsSummary = IDL.Record({
  'eventCommission' : IDL.Nat,
  'activityBonus' : IDL.Nat,
  'totalPaid' : IDL.Nat,
  'totalLifetime' : IDL.Nat,
  'directReferral' : IDL.Nat,
  'levelOverride' : IDL.Nat,
  'totalPending' : IDL.Nat,
  'royaltyPool' : IDL.Nat,
  'finFracFran' : IDL.Nat,
});
export const FSURecord = IDL.Record({
  'member' : IDL.Principal,
  'balance' : IDL.Nat,
  'lifetimeEarned' : IDL.Nat,
});
export const FSUTxType = IDL.Variant({
  'redeemed' : IDL.Null,
  'transferred' : IDL.Null,
  'earned' : IDL.Null,
});
export const FSUTransaction = IDL.Record({
  'id' : IDL.Text,
  'member' : IDL.Principal,
  'valuePerUnitCents' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'txType' : FSUTxType,
  'amount' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'error' : IDL.Null,
  'success' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'createdAt' : IDL.Int,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const OrgStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const OrgMemberRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
});
export const OrgMember = IDL.Record({
  'userId' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : OrgMemberRole,
});
export const Organization = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'status' : OrgStatus,
  'members' : IDL.Vec(OrgMember),
  'orgType' : IDL.Text,
  'foundedYear' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'website' : IDL.Text,
});
export const ProposalStatus = IDL.Variant({
  'review' : IDL.Null,
  'closed' : IDL.Null,
  'cancelled' : IDL.Null,
  'enacted' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
  'openVote' : IDL.Null,
});
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProposalStatus,
  'title' : IDL.Text,
  'mechanism' : VotingMechanism,
  'enactedAt' : IDL.Opt(IDL.Int),
  'orgId' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'quorumPercent' : IDL.Nat,
  'tenantId' : IDL.Text,
  'proposalType' : ProposalType,
  'votingClosesAt' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Int,
  'votingOpensAt' : IDL.Opt(IDL.Int),
  'voteWindowHours' : IDL.Nat,
  'proposer' : IDL.Principal,
  'sponsors' : IDL.Vec(IDL.Principal),
  'sponsorThreshold' : IDL.Nat,
});
export const DebateComment = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'parentCommentId' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
  'editedAt' : IDL.Opt(IDL.Int),
  'proposalId' : IDL.Nat,
});
export const ForumReply = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'isModeratorReply' : IDL.Bool,
  'threadId' : IDL.Nat,
});
export const RoyaltyPool = IDL.Record({
  'id' : IDL.Text,
  'isDistributed' : IDL.Bool,
  'period' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalUnits' : IDL.Nat,
  'poolType' : RoyaltyPoolType,
});
export const ThreadStatus = IDL.Variant({
  'open' : IDL.Null,
  'locked' : IDL.Null,
  'archived' : IDL.Null,
});
export const ForumThread = IDL.Record({
  'id' : IDL.Nat,
  'status' : ThreadStatus,
  'title' : IDL.Text,
  'orgId' : IDL.Opt(IDL.Text),
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'viewCount' : IDL.Nat,
  'replyCount' : IDL.Nat,
  'category' : ForumCategory,
  'isPinned' : IDL.Bool,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'walletAddress' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : TransactionType,
  'amountICP' : IDL.Float64,
});
export const VoteTally = IDL.Record({
  'noVotes' : IDL.Nat,
  'abstainWeight' : IDL.Nat,
  'yesWeight' : IDL.Nat,
  'totalVoters' : IDL.Nat,
  'mechanism' : VotingMechanism,
  'yesVotes' : IDL.Nat,
  'quorumPercent' : IDL.Nat,
  'totalVotesCast' : IDL.Nat,
  'rankedResults' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'quorumMet' : IDL.Bool,
  'tallyComputedAt' : IDL.Int,
  'abstainVotes' : IDL.Nat,
  'noWeight' : IDL.Nat,
  'proposalId' : IDL.Nat,
  'passed' : IDL.Bool,
});
export const BillingRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amountCents' : IDL.Nat,
  'tenantId' : IDL.Text,
});
export const TenantMember = IDL.Record({
  'principal' : IDL.Principal,
  'role' : IDL.Text,
  'tenantId' : IDL.Text,
  'addedAt' : IDL.Int,
});
export const Role = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
  'moderator' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserSummary = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : Role,
  'isActive' : IDL.Bool,
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBillingRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addDebateComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addTenantMember' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addToFSUPool' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addToRoyaltyPool' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, TransactionType],
      [],
      [],
    ),
  'adminListAllCrowdfundingCampaigns' : IDL.Func(
      [],
      [IDL.Vec(CrowdfundingCampaign)],
      ['query'],
    ),
  'adminListCrowdfundingPledges' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CrowdfundingPledge)],
      ['query'],
    ),
  'approveCrowdfundingCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'archiveCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'archiveOrg' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'archiveThread' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelProposal' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'cancelTenant' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'castVote' : IDL.Func(
      [IDL.Nat, VoteChoice, IDL.Vec(RankedChoiceEntry)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'checkAndExpireTrials' : IDL.Func(
      [],
      [IDL.Record({ 'checked' : IDL.Nat, 'expired' : IDL.Nat })],
      [],
    ),
  'closeProposal' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CampaignType,
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createCrowdfundingCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CrowdfundingCategory,
        CrowdfundingFundingModel,
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Vec(CrowdfundingRewardTier),
        IDL.Vec(CrowdfundingMilestone),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Text],
      [],
    ),
  'createOrg' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'createProposal' : IDL.Func(
      [
        ProposalType,
        IDL.Text,
        IDL.Text,
        VotingMechanism,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createRoyaltyPool' : IDL.Func([RoyaltyPoolType, IDL.Text], [IDL.Text], []),
  'createTenant' : IDL.Func(
      [IDL.Text, TenantTier, IDL.Opt(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'createThread' : IDL.Func(
      [IDL.Text, IDL.Text, ForumCategory, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deactivateCommissionRate' : IDL.Func(
      [MembershipTierLevel, IDL.Nat, EarningType],
      [IDL.Bool],
      [],
    ),
  'delegateVote' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'distributeFSU' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'distributeRoyaltyPool' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'editDebateComment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'enactProposal' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'finalizeCrowdfundingCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Text], [IDL.Opt(Campaign)], ['query']),
  'getCampaignPledges' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CrowdfundingPledge)],
      ['query'],
    ),
  'getCampaignProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'goal' : IDL.Nat, 'progress' : IDL.Nat }))],
      ['query'],
    ),
  'getCampaignSupporterCount' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getCommissionRate' : IDL.Func(
      [MembershipTierLevel, IDL.Nat, EarningType],
      [IDL.Opt(CommissionRate)],
      ['query'],
    ),
  'getCommissionRates' : IDL.Func([], [IDL.Vec(CommissionRate)], ['query']),
  'getCrowdfundingCampaign' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CrowdfundingCampaign)],
      ['query'],
    ),
  'getCrowdfundingConfig' : IDL.Func([], [CrowdfundingConfig], ['query']),
  'getCrowdfundingPledge' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CrowdfundingPledge)],
      ['query'],
    ),
  'getExpiringTrials' : IDL.Func([IDL.Nat], [IDL.Vec(Tenant)], ['query']),
  'getFSUPoolStatus' : IDL.Func([], [FSUPoolStatus], ['query']),
  'getLinkedWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
  'getMemberEarnings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EarningRecord)],
      ['query'],
    ),
  'getMemberTierRecord' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberTierRecord)],
      ['query'],
    ),
  'getMemberVote' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Opt(Vote)],
      ['query'],
    ),
  'getMyDelegation' : IDL.Func([], [IDL.Opt(DelegationRecord)], ['query']),
  'getMyDownline' : IDL.Func([], [IDL.Vec(DownlineMember)], ['query']),
  'getMyEarnings' : IDL.Func([], [IDL.Vec(EarningRecord)], ['query']),
  'getMyEarningsSummary' : IDL.Func([], [EarningsSummary], ['query']),
  'getMyFSURecord' : IDL.Func([], [IDL.Opt(FSURecord)], ['query']),
  'getMyFSUTransactions' : IDL.Func([], [IDL.Vec(FSUTransaction)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyPledges' : IDL.Func([], [IDL.Vec(CrowdfundingPledge)], ['query']),
  'getMyReferralCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyRoyaltyDistributions' : IDL.Func(
      [],
      [IDL.Vec(EarningRecord)],
      ['query'],
    ),
  'getMyTenant' : IDL.Func([], [IDL.Opt(Tenant)], ['query']),
  'getMyTierRecord' : IDL.Func([], [IDL.Opt(MemberTierRecord)], ['query']),
  'getMyUplineChain' : IDL.Func([], [IDL.Vec(MemberTierRecord)], ['query']),
  'getOrg' : IDL.Func([IDL.Text], [IDL.Opt(Organization)], ['query']),
  'getOrgMembers' : IDL.Func([IDL.Text], [IDL.Vec(OrgMember)], ['query']),
  'getPreferredLanguage' : IDL.Func([], [IDL.Text], ['query']),
  'getProposal' : IDL.Func([IDL.Nat], [IDL.Opt(Proposal)], ['query']),
  'getProposalComments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DebateComment)],
      ['query'],
    ),
  'getProposalSponsors' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getQuorumStatus' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'totalVoters' : IDL.Nat,
          'quorumPercent' : IDL.Nat,
          'percentVoted' : IDL.Nat,
          'quorumMet' : IDL.Bool,
          'votesCast' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReplies' : IDL.Func([IDL.Nat], [IDL.Vec(ForumReply)], ['query']),
  'getRoyaltyPool' : IDL.Func([IDL.Text], [IDL.Opt(RoyaltyPool)], ['query']),
  'getTenant' : IDL.Func([IDL.Text], [IDL.Opt(Tenant)], ['query']),
  'getTenantBranding' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TenantBranding)],
      ['query'],
    ),
  'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(ForumThread)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTrialAutomationStatus' : IDL.Func(
      [],
      [IDL.Record({ 'lastCheck' : IDL.Int, 'nextCheckIn' : IDL.Text })],
      ['query'],
    ),
  'getUserOrgs' : IDL.Func([IDL.Text], [IDL.Vec(Organization)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteTally' : IDL.Func([IDL.Nat], [IDL.Opt(VoteTally)], ['query']),
  'getVotesByProposal' : IDL.Func([IDL.Nat], [IDL.Vec(Vote)], ['query']),
  'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'incrementThreadView' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'initMemberMLM' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'joinOrg' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'leaveCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'leaveOrg' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'linkWallet' : IDL.Func([WalletType, IDL.Text, IDL.Text], [], []),
  'listActiveCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'listActiveOrgs' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
  'listActiveProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'listAllMemberTiers' : IDL.Func([], [IDL.Vec(MemberTierRecord)], ['query']),
  'listBillingHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BillingRecord)],
      ['query'],
    ),
  'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'listCampaignsByOrg' : IDL.Func([IDL.Text], [IDL.Vec(Campaign)], ['query']),
  'listCrowdfundingCampaigns' : IDL.Func(
      [],
      [IDL.Vec(CrowdfundingCampaign)],
      ['query'],
    ),
  'listCrowdfundingCampaignsByCategory' : IDL.Func(
      [CrowdfundingCategory],
      [IDL.Vec(CrowdfundingCampaign)],
      ['query'],
    ),
  'listMyCrowdfundingCampaigns' : IDL.Func(
      [],
      [IDL.Vec(CrowdfundingCampaign)],
      ['query'],
    ),
  'listOrgs' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
  'listProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'listProposalsByStatus' : IDL.Func(
      [ProposalStatus],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'listProposalsByType' : IDL.Func(
      [ProposalType],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'listRoyaltyPools' : IDL.Func([], [IDL.Vec(RoyaltyPool)], ['query']),
  'listTenantMembers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TenantMember)],
      ['query'],
    ),
  'listTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'listThreads' : IDL.Func([], [IDL.Vec(ForumThread)], ['query']),
  'listThreadsByCategory' : IDL.Func(
      [ForumCategory],
      [IDL.Vec(ForumThread)],
      ['query'],
    ),
  'listThreadsByOrg' : IDL.Func([IDL.Text], [IDL.Vec(ForumThread)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'lockThread' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'markEarningPaid' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'openProposalForVoting' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'pinThread' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'pledgeToCrowdfundingCampaign' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'processReferralChainBonus' : IDL.Func(
      [IDL.Principal, IDL.Nat, EarningType, IDL.Text],
      [],
      [],
    ),
  'reactivateTenant' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'recordEarning' : IDL.Func(
      [IDL.Principal, IDL.Nat, EarningType, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'redeemFSU' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'refundPledge' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'rejectCrowdfundingCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeTenantMember' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
  'replyToThread' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'resolveReferralCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'revokeDelegation' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'runPayCycle' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendTrialExpiryNotifications' : IDL.Func([], [IDL.Text], []),
  'setCommissionRate' : IDL.Func(
      [MembershipTierLevel, IDL.Nat, EarningType, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'setCrowdfundingConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'setMemberTier' : IDL.Func(
      [IDL.Principal, MembershipTierLevel],
      [IDL.Bool],
      [],
    ),
  'setPreferredLanguage' : IDL.Func([IDL.Text], [], []),
  'sponsorProposal' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'suspendTenant' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'unlinkWallet' : IDL.Func([IDL.Text], [], []),
  'updateCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        CampaignType,
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'updateCrowdfundingCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateOrg' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Bool],
      [],
    ),
  'updateTenantBranding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'upgradeMemberTier' : IDL.Func([MembershipTierLevel], [IDL.Bool], []),
  'withdrawSponsor' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'sent' : IDL.Null,
    'received' : IDL.Null,
  });
  const CrowdfundingStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'funded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CrowdfundingRewardTier = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'maxBackers' : IDL.Opt(IDL.Nat),
    'backerCount' : IDL.Nat,
    'minPledgeCents' : IDL.Nat,
  });
  const CrowdfundingFundingModel = IDL.Variant({
    'allOrNothing' : IDL.Null,
    'keepWhatYouRaise' : IDL.Null,
  });
  const CrowdfundingCategory = IDL.Variant({
    'research' : IDL.Null,
    'civic' : IDL.Null,
    'education' : IDL.Null,
    'community' : IDL.Null,
    'crisisResponse' : IDL.Null,
    'humanitarian' : IDL.Null,
    'youth' : IDL.Null,
  });
  const CrowdfundingMilestone = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'achievedAt' : IDL.Opt(IDL.Int),
    'bonusFSUAmount' : IDL.Nat,
    'description' : IDL.Text,
    'targetCents' : IDL.Nat,
  });
  const CrowdfundingCampaign = IDL.Record({
    'id' : IDL.Text,
    'status' : CrowdfundingStatus,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'rewardTiers' : IDL.Vec(CrowdfundingRewardTier),
    'fundingModel' : CrowdfundingFundingModel,
    'approvedByAdmin' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'deadline' : IDL.Int,
    'tenantId' : IDL.Text,
    'goalCents' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'fsuContributionBps' : IDL.Nat,
    'backerCount' : IDL.Nat,
    'currency' : IDL.Text,
    'totalFSUDistributed' : IDL.Nat,
    'category' : CrowdfundingCategory,
    'raisedCents' : IDL.Nat,
    'milestones' : IDL.Vec(CrowdfundingMilestone),
  });
  const CrowdfundingPledge = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'referrerCode' : IDL.Opt(IDL.Text),
    'receiptCode' : IDL.Text,
    'createdAt' : IDL.Int,
    'backer' : IDL.Principal,
    'campaignId' : IDL.Text,
    'amountCents' : IDL.Nat,
    'rewardTierId' : IDL.Opt(IDL.Text),
    'fsuEarned' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VoteChoice = IDL.Variant({
    'no' : IDL.Null,
    'yes' : IDL.Null,
    'abstain' : IDL.Null,
  });
  const RankedChoiceEntry = IDL.Record({
    'rank' : IDL.Nat,
    'candidateId' : IDL.Text,
  });
  const CampaignType = IDL.Variant({
    'action' : IDL.Null,
    'awareness' : IDL.Null,
    'fundraiser' : IDL.Null,
    'petition' : IDL.Null,
  });
  const ProposalType = IDL.Variant({
    'resolution' : IDL.Null,
    'communityInitiative' : IDL.Null,
    'amendment' : IDL.Null,
    'budget' : IDL.Null,
    'policy' : IDL.Null,
  });
  const VotingMechanism = IDL.Variant({
    'simpleMajority' : IDL.Null,
    'liquidDelegation' : IDL.Null,
    'supermajority66' : IDL.Null,
    'supermajority75' : IDL.Null,
    'rankedChoice' : IDL.Null,
  });
  const RoyaltyPoolType = IDL.Variant({
    'event' : IDL.Null,
    'leadership' : IDL.Null,
    'global' : IDL.Null,
    'finFracFran' : IDL.Null,
  });
  const TenantTier = IDL.Variant({
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
    'organization' : IDL.Null,
  });
  const ForumCategory = IDL.Variant({
    'resources' : IDL.Null,
    'general' : IDL.Null,
    'regional' : IDL.Null,
    'campaigns' : IDL.Null,
    'activism' : IDL.Null,
    'announcements' : IDL.Null,
  });
  const MembershipTierLevel = IDL.Variant({
    'free' : IDL.Null,
    'founder' : IDL.Null,
    'executive' : IDL.Null,
    'affiliate' : IDL.Null,
    'ambassador' : IDL.Null,
    'partner' : IDL.Null,
    'associate' : IDL.Null,
  });
  const EarningType = IDL.Variant({
    'eventCommission' : IDL.Null,
    'activityBonus' : IDL.Null,
    'directReferral' : IDL.Null,
    'levelOverride' : IDL.Null,
    'royaltyPool' : IDL.Null,
    'finFracFran' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const CampaignStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : CampaignStatus,
    'title' : IDL.Text,
    'endDate' : IDL.Int,
    'orgId' : IDL.Text,
    'goal' : IDL.Nat,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'supporterCount' : IDL.Nat,
    'campaignType' : CampaignType,
    'startDate' : IDL.Int,
  });
  const CommissionRate = IDL.Record({
    'basisPoints' : IDL.Nat,
    'tier' : MembershipTierLevel,
    'flatAmountUnits' : IDL.Nat,
    'isActive' : IDL.Bool,
    'earningType' : EarningType,
    'depthLevel' : IDL.Nat,
  });
  const CrowdfundingConfig = IDL.Record({
    'defaultFSUContributionBps' : IDL.Nat,
    'milestoneAchievementBonusBps' : IDL.Nat,
    'creatorFSUBonus' : IDL.Nat,
  });
  const TenantStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const TenantSubscription = IDL.Record({
    'monthlyCents' : IDL.Nat,
    'tier' : TenantTier,
    'renewalDate' : IDL.Int,
    'startDate' : IDL.Int,
  });
  const TenantBranding = IDL.Record({
    'orgName' : IDL.Text,
    'primaryColor' : IDL.Text,
    'logoUrl' : IDL.Text,
    'welcomeMessage' : IDL.Text,
  });
  const Tenant = IDL.Record({
    'id' : IDL.Text,
    'status' : TenantStatus,
    'subscription' : IDL.Opt(TenantSubscription),
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberCount' : IDL.Nat,
    'tier' : TenantTier,
    'storageUsedMb' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'branding' : IDL.Opt(TenantBranding),
    'trialEndsAt' : IDL.Opt(IDL.Int),
  });
  const FSUPoolStatus = IDL.Record({
    'totalOutstandingFSU' : IDL.Nat,
    'valuePerUnitCents' : IDL.Nat,
    'poolSizeUnits' : IDL.Nat,
    'nextDistributionLabel' : IDL.Text,
  });
  const WalletType = IDL.Variant({
    'internetIdentity' : IDL.Null,
    'plug' : IDL.Null,
    'stoic' : IDL.Null,
  });
  const Wallet = IDL.Record({
    'linkedAt' : IDL.Int,
    'walletType' : WalletType,
    'address' : IDL.Text,
    'balanceICP' : IDL.Float64,
    'walletLabel' : IDL.Text,
  });
  const EarningStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'processing' : IDL.Null,
  });
  const EarningRecord = IDL.Record({
    'id' : IDL.Text,
    'member' : IDL.Principal,
    'status' : EarningStatus,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sourceId' : IDL.Text,
    'earningType' : EarningType,
    'amountUnits' : IDL.Nat,
    'depthLevel' : IDL.Nat,
  });
  const MemberTierRecord = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'joinedAt' : IDL.Int,
    'tier' : MembershipTierLevel,
    'upgradedAt' : IDL.Int,
    'sponsorPrincipal' : IDL.Opt(IDL.Principal),
    'sponsorCode' : IDL.Opt(IDL.Text),
  });
  const Vote = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Nat,
    'voter' : IDL.Principal,
    'delegatedTo' : IDL.Opt(IDL.Principal),
    'castAt' : IDL.Int,
    'choice' : VoteChoice,
    'proposalId' : IDL.Nat,
    'rankedChoices' : IDL.Vec(RankedChoiceEntry),
  });
  const DelegationRecord = IDL.Record({
    'delegateTo' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'delegator' : IDL.Principal,
    'proposalId' : IDL.Opt(IDL.Nat),
    'revokedAt' : IDL.Opt(IDL.Int),
  });
  const DownlineMember = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'joinedAt' : IDL.Int,
    'tier' : MembershipTierLevel,
    'directReferralCount' : IDL.Nat,
  });
  const EarningsSummary = IDL.Record({
    'eventCommission' : IDL.Nat,
    'activityBonus' : IDL.Nat,
    'totalPaid' : IDL.Nat,
    'totalLifetime' : IDL.Nat,
    'directReferral' : IDL.Nat,
    'levelOverride' : IDL.Nat,
    'totalPending' : IDL.Nat,
    'royaltyPool' : IDL.Nat,
    'finFracFran' : IDL.Nat,
  });
  const FSURecord = IDL.Record({
    'member' : IDL.Principal,
    'balance' : IDL.Nat,
    'lifetimeEarned' : IDL.Nat,
  });
  const FSUTxType = IDL.Variant({
    'redeemed' : IDL.Null,
    'transferred' : IDL.Null,
    'earned' : IDL.Null,
  });
  const FSUTransaction = IDL.Record({
    'id' : IDL.Text,
    'member' : IDL.Principal,
    'valuePerUnitCents' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'txType' : FSUTxType,
    'amount' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'error' : IDL.Null,
    'success' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'createdAt' : IDL.Int,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const OrgStatus = IDL.Variant({ 'active' : IDL.Null, 'archived' : IDL.Null });
  const OrgMemberRole = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
  });
  const OrgMember = IDL.Record({
    'userId' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : OrgMemberRole,
  });
  const Organization = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'status' : OrgStatus,
    'members' : IDL.Vec(OrgMember),
    'orgType' : IDL.Text,
    'foundedYear' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'website' : IDL.Text,
  });
  const ProposalStatus = IDL.Variant({
    'review' : IDL.Null,
    'closed' : IDL.Null,
    'cancelled' : IDL.Null,
    'enacted' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
    'openVote' : IDL.Null,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProposalStatus,
    'title' : IDL.Text,
    'mechanism' : VotingMechanism,
    'enactedAt' : IDL.Opt(IDL.Int),
    'orgId' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'quorumPercent' : IDL.Nat,
    'tenantId' : IDL.Text,
    'proposalType' : ProposalType,
    'votingClosesAt' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Int,
    'votingOpensAt' : IDL.Opt(IDL.Int),
    'voteWindowHours' : IDL.Nat,
    'proposer' : IDL.Principal,
    'sponsors' : IDL.Vec(IDL.Principal),
    'sponsorThreshold' : IDL.Nat,
  });
  const DebateComment = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'parentCommentId' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
    'editedAt' : IDL.Opt(IDL.Int),
    'proposalId' : IDL.Nat,
  });
  const ForumReply = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'isModeratorReply' : IDL.Bool,
    'threadId' : IDL.Nat,
  });
  const RoyaltyPool = IDL.Record({
    'id' : IDL.Text,
    'isDistributed' : IDL.Bool,
    'period' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalUnits' : IDL.Nat,
    'poolType' : RoyaltyPoolType,
  });
  const ThreadStatus = IDL.Variant({
    'open' : IDL.Null,
    'locked' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ForumThread = IDL.Record({
    'id' : IDL.Nat,
    'status' : ThreadStatus,
    'title' : IDL.Text,
    'orgId' : IDL.Opt(IDL.Text),
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'viewCount' : IDL.Nat,
    'replyCount' : IDL.Nat,
    'category' : ForumCategory,
    'isPinned' : IDL.Bool,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'walletAddress' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : TransactionType,
    'amountICP' : IDL.Float64,
  });
  const VoteTally = IDL.Record({
    'noVotes' : IDL.Nat,
    'abstainWeight' : IDL.Nat,
    'yesWeight' : IDL.Nat,
    'totalVoters' : IDL.Nat,
    'mechanism' : VotingMechanism,
    'yesVotes' : IDL.Nat,
    'quorumPercent' : IDL.Nat,
    'totalVotesCast' : IDL.Nat,
    'rankedResults' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'quorumMet' : IDL.Bool,
    'tallyComputedAt' : IDL.Int,
    'abstainVotes' : IDL.Nat,
    'noWeight' : IDL.Nat,
    'proposalId' : IDL.Nat,
    'passed' : IDL.Bool,
  });
  const BillingRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amountCents' : IDL.Nat,
    'tenantId' : IDL.Text,
  });
  const TenantMember = IDL.Record({
    'principal' : IDL.Principal,
    'role' : IDL.Text,
    'tenantId' : IDL.Text,
    'addedAt' : IDL.Int,
  });
  const Role = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserSummary = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : Role,
    'isActive' : IDL.Bool,
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBillingRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addDebateComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addTenantMember' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addToFSUPool' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addToRoyaltyPool' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, TransactionType],
        [],
        [],
      ),
    'adminListAllCrowdfundingCampaigns' : IDL.Func(
        [],
        [IDL.Vec(CrowdfundingCampaign)],
        ['query'],
      ),
    'adminListCrowdfundingPledges' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CrowdfundingPledge)],
        ['query'],
      ),
    'approveCrowdfundingCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'archiveCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'archiveOrg' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'archiveThread' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelProposal' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'cancelTenant' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'castVote' : IDL.Func(
        [IDL.Nat, VoteChoice, IDL.Vec(RankedChoiceEntry)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'checkAndExpireTrials' : IDL.Func(
        [],
        [IDL.Record({ 'checked' : IDL.Nat, 'expired' : IDL.Nat })],
        [],
      ),
    'closeProposal' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CampaignType,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createCrowdfundingCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CrowdfundingCategory,
          CrowdfundingFundingModel,
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Vec(CrowdfundingRewardTier),
          IDL.Vec(CrowdfundingMilestone),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Text],
        [],
      ),
    'createOrg' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'createProposal' : IDL.Func(
        [
          ProposalType,
          IDL.Text,
          IDL.Text,
          VotingMechanism,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createRoyaltyPool' : IDL.Func([RoyaltyPoolType, IDL.Text], [IDL.Text], []),
    'createTenant' : IDL.Func(
        [IDL.Text, TenantTier, IDL.Opt(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'createThread' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ForumCategory,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deactivateCommissionRate' : IDL.Func(
        [MembershipTierLevel, IDL.Nat, EarningType],
        [IDL.Bool],
        [],
      ),
    'delegateVote' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'distributeFSU' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'distributeRoyaltyPool' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'editDebateComment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'enactProposal' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'finalizeCrowdfundingCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Text], [IDL.Opt(Campaign)], ['query']),
    'getCampaignPledges' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CrowdfundingPledge)],
        ['query'],
      ),
    'getCampaignProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'goal' : IDL.Nat, 'progress' : IDL.Nat }))],
        ['query'],
      ),
    'getCampaignSupporterCount' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getCommissionRate' : IDL.Func(
        [MembershipTierLevel, IDL.Nat, EarningType],
        [IDL.Opt(CommissionRate)],
        ['query'],
      ),
    'getCommissionRates' : IDL.Func([], [IDL.Vec(CommissionRate)], ['query']),
    'getCrowdfundingCampaign' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CrowdfundingCampaign)],
        ['query'],
      ),
    'getCrowdfundingConfig' : IDL.Func([], [CrowdfundingConfig], ['query']),
    'getCrowdfundingPledge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CrowdfundingPledge)],
        ['query'],
      ),
    'getExpiringTrials' : IDL.Func([IDL.Nat], [IDL.Vec(Tenant)], ['query']),
    'getFSUPoolStatus' : IDL.Func([], [FSUPoolStatus], ['query']),
    'getLinkedWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
    'getMemberEarnings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EarningRecord)],
        ['query'],
      ),
    'getMemberTierRecord' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberTierRecord)],
        ['query'],
      ),
    'getMemberVote' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Opt(Vote)],
        ['query'],
      ),
    'getMyDelegation' : IDL.Func([], [IDL.Opt(DelegationRecord)], ['query']),
    'getMyDownline' : IDL.Func([], [IDL.Vec(DownlineMember)], ['query']),
    'getMyEarnings' : IDL.Func([], [IDL.Vec(EarningRecord)], ['query']),
    'getMyEarningsSummary' : IDL.Func([], [EarningsSummary], ['query']),
    'getMyFSURecord' : IDL.Func([], [IDL.Opt(FSURecord)], ['query']),
    'getMyFSUTransactions' : IDL.Func([], [IDL.Vec(FSUTransaction)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyPledges' : IDL.Func([], [IDL.Vec(CrowdfundingPledge)], ['query']),
    'getMyReferralCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyRoyaltyDistributions' : IDL.Func(
        [],
        [IDL.Vec(EarningRecord)],
        ['query'],
      ),
    'getMyTenant' : IDL.Func([], [IDL.Opt(Tenant)], ['query']),
    'getMyTierRecord' : IDL.Func([], [IDL.Opt(MemberTierRecord)], ['query']),
    'getMyUplineChain' : IDL.Func([], [IDL.Vec(MemberTierRecord)], ['query']),
    'getOrg' : IDL.Func([IDL.Text], [IDL.Opt(Organization)], ['query']),
    'getOrgMembers' : IDL.Func([IDL.Text], [IDL.Vec(OrgMember)], ['query']),
    'getPreferredLanguage' : IDL.Func([], [IDL.Text], ['query']),
    'getProposal' : IDL.Func([IDL.Nat], [IDL.Opt(Proposal)], ['query']),
    'getProposalComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DebateComment)],
        ['query'],
      ),
    'getProposalSponsors' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getQuorumStatus' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'totalVoters' : IDL.Nat,
            'quorumPercent' : IDL.Nat,
            'percentVoted' : IDL.Nat,
            'quorumMet' : IDL.Bool,
            'votesCast' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReplies' : IDL.Func([IDL.Nat], [IDL.Vec(ForumReply)], ['query']),
    'getRoyaltyPool' : IDL.Func([IDL.Text], [IDL.Opt(RoyaltyPool)], ['query']),
    'getTenant' : IDL.Func([IDL.Text], [IDL.Opt(Tenant)], ['query']),
    'getTenantBranding' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TenantBranding)],
        ['query'],
      ),
    'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(ForumThread)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTrialAutomationStatus' : IDL.Func(
        [],
        [IDL.Record({ 'lastCheck' : IDL.Int, 'nextCheckIn' : IDL.Text })],
        ['query'],
      ),
    'getUserOrgs' : IDL.Func([IDL.Text], [IDL.Vec(Organization)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteTally' : IDL.Func([IDL.Nat], [IDL.Opt(VoteTally)], ['query']),
    'getVotesByProposal' : IDL.Func([IDL.Nat], [IDL.Vec(Vote)], ['query']),
    'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'incrementThreadView' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'initMemberMLM' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'joinOrg' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'leaveCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'leaveOrg' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'linkWallet' : IDL.Func([WalletType, IDL.Text, IDL.Text], [], []),
    'listActiveCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'listActiveOrgs' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
    'listActiveProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'listAllMemberTiers' : IDL.Func([], [IDL.Vec(MemberTierRecord)], ['query']),
    'listBillingHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BillingRecord)],
        ['query'],
      ),
    'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'listCampaignsByOrg' : IDL.Func([IDL.Text], [IDL.Vec(Campaign)], ['query']),
    'listCrowdfundingCampaigns' : IDL.Func(
        [],
        [IDL.Vec(CrowdfundingCampaign)],
        ['query'],
      ),
    'listCrowdfundingCampaignsByCategory' : IDL.Func(
        [CrowdfundingCategory],
        [IDL.Vec(CrowdfundingCampaign)],
        ['query'],
      ),
    'listMyCrowdfundingCampaigns' : IDL.Func(
        [],
        [IDL.Vec(CrowdfundingCampaign)],
        ['query'],
      ),
    'listOrgs' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
    'listProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'listProposalsByStatus' : IDL.Func(
        [ProposalStatus],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'listProposalsByType' : IDL.Func(
        [ProposalType],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'listRoyaltyPools' : IDL.Func([], [IDL.Vec(RoyaltyPool)], ['query']),
    'listTenantMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TenantMember)],
        ['query'],
      ),
    'listTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'listThreads' : IDL.Func([], [IDL.Vec(ForumThread)], ['query']),
    'listThreadsByCategory' : IDL.Func(
        [ForumCategory],
        [IDL.Vec(ForumThread)],
        ['query'],
      ),
    'listThreadsByOrg' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ForumThread)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'lockThread' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'markEarningPaid' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'openProposalForVoting' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'pinThread' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'pledgeToCrowdfundingCampaign' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'processReferralChainBonus' : IDL.Func(
        [IDL.Principal, IDL.Nat, EarningType, IDL.Text],
        [],
        [],
      ),
    'reactivateTenant' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'recordEarning' : IDL.Func(
        [IDL.Principal, IDL.Nat, EarningType, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'redeemFSU' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'refundPledge' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'rejectCrowdfundingCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeTenantMember' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
    'replyToThread' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'resolveReferralCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'revokeDelegation' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'runPayCycle' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendTrialExpiryNotifications' : IDL.Func([], [IDL.Text], []),
    'setCommissionRate' : IDL.Func(
        [MembershipTierLevel, IDL.Nat, EarningType, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'setCrowdfundingConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'setMemberTier' : IDL.Func(
        [IDL.Principal, MembershipTierLevel],
        [IDL.Bool],
        [],
      ),
    'setPreferredLanguage' : IDL.Func([IDL.Text], [], []),
    'sponsorProposal' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'suspendTenant' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'unlinkWallet' : IDL.Func([IDL.Text], [], []),
    'updateCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          CampaignType,
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateCrowdfundingCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateOrg' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'updateTenantBranding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'upgradeMemberTier' : IDL.Func([MembershipTierLevel], [IDL.Bool], []),
    'withdrawSponsor' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };