/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingRecord {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'amountCents' : bigint,
  'tenantId' : string,
}
export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'title' : string,
  'endDate' : bigint,
  'orgId' : string,
  'goal' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'description' : string,
  'progress' : bigint,
  'supporterCount' : bigint,
  'campaignType' : CampaignType,
  'startDate' : bigint,
}
export type CampaignStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export type CampaignType = { 'action' : null } |
  { 'awareness' : null } |
  { 'fundraiser' : null } |
  { 'petition' : null };
export interface CommissionRate {
  'basisPoints' : bigint,
  'tier' : MembershipTierLevel,
  'flatAmountUnits' : bigint,
  'isActive' : boolean,
  'earningType' : EarningType,
  'depthLevel' : bigint,
}
export interface CrowdfundingCampaign {
  'id' : string,
  'status' : CrowdfundingStatus,
  'coverImageUrl' : string,
  'title' : string,
  'creator' : Principal,
  'rewardTiers' : Array<CrowdfundingRewardTier>,
  'fundingModel' : CrowdfundingFundingModel,
  'approvedByAdmin' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'deadline' : bigint,
  'tenantId' : string,
  'goalCents' : bigint,
  'updatedAt' : bigint,
  'fsuContributionBps' : bigint,
  'backerCount' : bigint,
  'currency' : string,
  'totalFSUDistributed' : bigint,
  'category' : CrowdfundingCategory,
  'raisedCents' : bigint,
  'milestones' : Array<CrowdfundingMilestone>,
}
export type CrowdfundingCategory = { 'research' : null } |
  { 'civic' : null } |
  { 'education' : null } |
  { 'community' : null } |
  { 'crisisResponse' : null } |
  { 'humanitarian' : null } |
  { 'youth' : null };
export interface CrowdfundingConfig {
  'defaultFSUContributionBps' : bigint,
  'milestoneAchievementBonusBps' : bigint,
  'creatorFSUBonus' : bigint,
}
export type CrowdfundingFundingModel = { 'allOrNothing' : null } |
  { 'keepWhatYouRaise' : null };
export interface CrowdfundingMilestone {
  'id' : string,
  'title' : string,
  'achievedAt' : [] | [bigint],
  'bonusFSUAmount' : bigint,
  'description' : string,
  'targetCents' : bigint,
}
export interface CrowdfundingPledge {
  'id' : string,
  'status' : string,
  'referrerCode' : [] | [string],
  'receiptCode' : string,
  'createdAt' : bigint,
  'backer' : Principal,
  'campaignId' : string,
  'amountCents' : bigint,
  'rewardTierId' : [] | [string],
  'fsuEarned' : bigint,
}
export interface CrowdfundingRewardTier {
  'id' : string,
  'title' : string,
  'description' : string,
  'maxBackers' : [] | [bigint],
  'backerCount' : bigint,
  'minPledgeCents' : bigint,
}
export type CrowdfundingStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'funded' : null } |
  { 'failed' : null };
export interface DownlineMember {
  'principal' : Principal,
  'referralCode' : string,
  'joinedAt' : bigint,
  'tier' : MembershipTierLevel,
  'directReferralCount' : bigint,
}
export interface EarningRecord {
  'id' : string,
  'member' : Principal,
  'status' : EarningStatus,
  'createdAt' : bigint,
  'description' : string,
  'sourceId' : string,
  'earningType' : EarningType,
  'amountUnits' : bigint,
  'depthLevel' : bigint,
}
export type EarningStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'processing' : null };
export type EarningType = { 'eventCommission' : null } |
  { 'activityBonus' : null } |
  { 'directReferral' : null } |
  { 'levelOverride' : null } |
  { 'royaltyPool' : null } |
  { 'finFracFran' : null };
export interface EarningsSummary {
  'eventCommission' : bigint,
  'activityBonus' : bigint,
  'totalPaid' : bigint,
  'totalLifetime' : bigint,
  'directReferral' : bigint,
  'levelOverride' : bigint,
  'totalPending' : bigint,
  'royaltyPool' : bigint,
  'finFracFran' : bigint,
}
export interface FSUPoolStatus {
  'totalOutstandingFSU' : bigint,
  'valuePerUnitCents' : bigint,
  'poolSizeUnits' : bigint,
  'nextDistributionLabel' : string,
}
export interface FSURecord {
  'member' : Principal,
  'balance' : bigint,
  'lifetimeEarned' : bigint,
}
export interface FSUTransaction {
  'id' : string,
  'member' : Principal,
  'valuePerUnitCents' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'txType' : FSUTxType,
  'amount' : bigint,
}
export type FSUTxType = { 'redeemed' : null } |
  { 'transferred' : null } |
  { 'earned' : null };
export type ForumCategory = { 'resources' : null } |
  { 'general' : null } |
  { 'regional' : null } |
  { 'campaigns' : null } |
  { 'activism' : null } |
  { 'announcements' : null };
export interface ForumReply {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'isModeratorReply' : boolean,
  'threadId' : bigint,
}
export interface ForumThread {
  'id' : bigint,
  'status' : ThreadStatus,
  'title' : string,
  'orgId' : [] | [string],
  'body' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'viewCount' : bigint,
  'replyCount' : bigint,
  'category' : ForumCategory,
  'isPinned' : boolean,
}
export interface MemberTierRecord {
  'principal' : Principal,
  'referralCode' : string,
  'joinedAt' : bigint,
  'tier' : MembershipTierLevel,
  'upgradedAt' : bigint,
  'sponsorPrincipal' : [] | [Principal],
  'sponsorCode' : [] | [string],
}
export type MembershipTierLevel = { 'free' : null } |
  { 'founder' : null } |
  { 'executive' : null } |
  { 'affiliate' : null } |
  { 'ambassador' : null } |
  { 'partner' : null } |
  { 'associate' : null };
export interface OrgMember {
  'userId' : string,
  'joinedAt' : bigint,
  'role' : OrgMemberRole,
}
export type OrgMemberRole = { 'member' : null } |
  { 'admin' : null };
export type OrgStatus = { 'active' : null } |
  { 'archived' : null };
export interface Organization {
  'id' : string,
  'region' : string,
  'status' : OrgStatus,
  'members' : Array<OrgMember>,
  'orgType' : string,
  'foundedYear' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'website' : string,
}
export type Role = { 'member' : null } |
  { 'admin' : null } |
  { 'moderator' : null } |
  { 'guest' : null };
export interface RoyaltyPool {
  'id' : string,
  'isDistributed' : boolean,
  'period' : string,
  'createdAt' : bigint,
  'totalUnits' : bigint,
  'poolType' : RoyaltyPoolType,
}
export type RoyaltyPoolType = { 'event' : null } |
  { 'leadership' : null } |
  { 'global' : null } |
  { 'finFracFran' : null };
export interface Tenant {
  'id' : string,
  'status' : TenantStatus,
  'subscription' : [] | [TenantSubscription],
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'tier' : TenantTier,
  'storageUsedMb' : bigint,
  'updatedAt' : bigint,
  'branding' : [] | [TenantBranding],
  'trialEndsAt' : [] | [bigint],
}
export interface TenantBranding {
  'orgName' : string,
  'primaryColor' : string,
  'logoUrl' : string,
  'welcomeMessage' : string,
}
export interface TenantMember {
  'principal' : Principal,
  'role' : string,
  'tenantId' : string,
  'addedAt' : bigint,
}
export type TenantStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'suspended' : null };
export interface TenantSubscription {
  'monthlyCents' : bigint,
  'tier' : TenantTier,
  'renewalDate' : bigint,
  'startDate' : bigint,
}
export type TenantTier = { 'enterprise' : null } |
  { 'starter' : null } |
  { 'organization' : null };
export type ThreadStatus = { 'open' : null } |
  { 'locked' : null } |
  { 'archived' : null };
export interface Transaction {
  'id' : bigint,
  'description' : string,
  'walletAddress' : string,
  'timestamp' : bigint,
  'txType' : TransactionType,
  'amountICP' : number,
}
export type TransactionType = { 'sent' : null } |
  { 'received' : null };
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'id' : string,
  'bio' : string,
  'displayName' : string,
  'joinedAt' : bigint,
  'role' : Role,
  'isActive' : boolean,
  'avatarUrl' : string,
}
export interface Wallet {
  'linkedAt' : bigint,
  'walletType' : WalletType,
  'address' : string,
  'balanceICP' : number,
  'walletLabel' : string,
}
export type WalletType = { 'internetIdentity' : null } |
  { 'plug' : null } |
  { 'stoic' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBillingRecord' : ActorMethod<[string, bigint, string, string], string>,
  'addTenantMember' : ActorMethod<[string, Principal, string], boolean>,
  'addToFSUPool' : ActorMethod<[bigint, string], undefined>,
  'addToRoyaltyPool' : ActorMethod<[string, bigint], boolean>,
  'addTransaction' : ActorMethod<
    [string, number, string, TransactionType],
    undefined
  >,
  'adminListAllCrowdfundingCampaigns' : ActorMethod<
    [],
    Array<CrowdfundingCampaign>
  >,
  'adminListCrowdfundingPledges' : ActorMethod<
    [string],
    Array<CrowdfundingPledge>
  >,
  'approveCrowdfundingCampaign' : ActorMethod<[string], boolean>,
  'archiveCampaign' : ActorMethod<[string], boolean>,
  'archiveOrg' : ActorMethod<[string], boolean>,
  'archiveThread' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTenant' : ActorMethod<[string], boolean>,
  /**
   * / Admin-only. Iterates all tenants and suspends any that are in #trial
   * / status with a trialEndsAt timestamp that has already passed.
   * / Returns the count of tenants checked and the count expired.
   */
  'checkAndExpireTrials' : ActorMethod<
    [],
    { 'checked' : bigint, 'expired' : bigint }
  >,
  'createCampaign' : ActorMethod<
    [
      string,
      string,
      CampaignType,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
    ],
    string
  >,
  'createCrowdfundingCampaign' : ActorMethod<
    [
      string,
      string,
      CrowdfundingCategory,
      CrowdfundingFundingModel,
      bigint,
      string,
      bigint,
      string,
      Array<CrowdfundingRewardTier>,
      Array<CrowdfundingMilestone>,
      [] | [bigint],
    ],
    string
  >,
  'createOrg' : ActorMethod<
    [string, string, string, string, string, bigint],
    string
  >,
  'createRoyaltyPool' : ActorMethod<[RoyaltyPoolType, string], string>,
  'createTenant' : ActorMethod<[string, TenantTier, [] | [bigint]], string>,
  'createThread' : ActorMethod<
    [string, string, ForumCategory, [] | [string], Array<string>],
    bigint
  >,
  'deactivateCommissionRate' : ActorMethod<
    [MembershipTierLevel, bigint, EarningType],
    boolean
  >,
  'distributeFSU' : ActorMethod<[bigint, string], undefined>,
  'distributeRoyaltyPool' : ActorMethod<[string, bigint], boolean>,
  'finalizeCrowdfundingCampaign' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[string], [] | [Campaign]>,
  'getCampaignPledges' : ActorMethod<[string], Array<CrowdfundingPledge>>,
  'getCampaignProgress' : ActorMethod<
    [string],
    [] | [{ 'goal' : bigint, 'progress' : bigint }]
  >,
  'getCampaignSupporterCount' : ActorMethod<[string], [] | [bigint]>,
  'getCommissionRate' : ActorMethod<
    [MembershipTierLevel, bigint, EarningType],
    [] | [CommissionRate]
  >,
  'getCommissionRates' : ActorMethod<[], Array<CommissionRate>>,
  'getCrowdfundingCampaign' : ActorMethod<
    [string],
    [] | [CrowdfundingCampaign]
  >,
  'getCrowdfundingConfig' : ActorMethod<[], CrowdfundingConfig>,
  'getCrowdfundingPledge' : ActorMethod<[string], [] | [CrowdfundingPledge]>,
  /**
   * / Returns all tenants whose trial will expire within the next `daysFromNow` days,
   * / including any that are already past their trial end date but not yet suspended.
   * / Sorted by trialEndsAt ascending (earliest expiry first).
   */
  'getExpiringTrials' : ActorMethod<[bigint], Array<Tenant>>,
  'getFSUPoolStatus' : ActorMethod<[], FSUPoolStatus>,
  'getLinkedWallets' : ActorMethod<[], Array<Wallet>>,
  'getMemberEarnings' : ActorMethod<[Principal], Array<EarningRecord>>,
  'getMemberTierRecord' : ActorMethod<[Principal], [] | [MemberTierRecord]>,
  'getMyDownline' : ActorMethod<[], Array<DownlineMember>>,
  'getMyEarnings' : ActorMethod<[], Array<EarningRecord>>,
  'getMyEarningsSummary' : ActorMethod<[], EarningsSummary>,
  'getMyFSURecord' : ActorMethod<[], [] | [FSURecord]>,
  'getMyFSUTransactions' : ActorMethod<[], Array<FSUTransaction>>,
  'getMyPledges' : ActorMethod<[], Array<CrowdfundingPledge>>,
  'getMyReferralCode' : ActorMethod<[], [] | [string]>,
  'getMyRoyaltyDistributions' : ActorMethod<[], Array<EarningRecord>>,
  'getMyTenant' : ActorMethod<[], [] | [Tenant]>,
  'getMyTierRecord' : ActorMethod<[], [] | [MemberTierRecord]>,
  'getMyUplineChain' : ActorMethod<[], Array<MemberTierRecord>>,
  'getOrg' : ActorMethod<[string], [] | [Organization]>,
  'getOrgMembers' : ActorMethod<[string], Array<OrgMember>>,
  'getPreferredLanguage' : ActorMethod<[], string>,
  'getReplies' : ActorMethod<[bigint], Array<ForumReply>>,
  'getRoyaltyPool' : ActorMethod<[string], [] | [RoyaltyPool]>,
  'getTenant' : ActorMethod<[string], [] | [Tenant]>,
  'getTenantBranding' : ActorMethod<[string], [] | [TenantBranding]>,
  'getThread' : ActorMethod<[bigint], [] | [ForumThread]>,
  'getTransactionHistory' : ActorMethod<[[] | [string]], Array<Transaction>>,
  'getUserOrgs' : ActorMethod<[string], Array<Organization>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[string], number>,
  'incrementThreadView' : ActorMethod<[bigint], boolean>,
  'initMemberMLM' : ActorMethod<[[] | [string]], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCampaign' : ActorMethod<[string], boolean>,
  'joinOrg' : ActorMethod<[string], boolean>,
  'leaveCampaign' : ActorMethod<[string], boolean>,
  'leaveOrg' : ActorMethod<[string], boolean>,
  'linkWallet' : ActorMethod<[WalletType, string, string], undefined>,
  'listActiveCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listActiveOrgs' : ActorMethod<[], Array<Organization>>,
  'listAllMemberTiers' : ActorMethod<[], Array<MemberTierRecord>>,
  'listBillingHistory' : ActorMethod<[string], Array<BillingRecord>>,
  'listCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listCampaignsByOrg' : ActorMethod<[string], Array<Campaign>>,
  'listCrowdfundingCampaigns' : ActorMethod<[], Array<CrowdfundingCampaign>>,
  'listCrowdfundingCampaignsByCategory' : ActorMethod<
    [CrowdfundingCategory],
    Array<CrowdfundingCampaign>
  >,
  'listMyCrowdfundingCampaigns' : ActorMethod<[], Array<CrowdfundingCampaign>>,
  'listOrgs' : ActorMethod<[], Array<Organization>>,
  'listRoyaltyPools' : ActorMethod<[], Array<RoyaltyPool>>,
  'listTenantMembers' : ActorMethod<[string], Array<TenantMember>>,
  'listTenants' : ActorMethod<[], Array<Tenant>>,
  'listThreads' : ActorMethod<[], Array<ForumThread>>,
  'listThreadsByCategory' : ActorMethod<[ForumCategory], Array<ForumThread>>,
  'listThreadsByOrg' : ActorMethod<[string], Array<ForumThread>>,
  'listUsers' : ActorMethod<[], Array<UserSummary>>,
  'lockThread' : ActorMethod<[bigint], boolean>,
  'markEarningPaid' : ActorMethod<[string], boolean>,
  'pinThread' : ActorMethod<[bigint], boolean>,
  'pledgeToCrowdfundingCampaign' : ActorMethod<
    [string, bigint, [] | [string], [] | [string]],
    string
  >,
  'processReferralChainBonus' : ActorMethod<
    [Principal, bigint, EarningType, string],
    undefined
  >,
  'reactivateTenant' : ActorMethod<[string], boolean>,
  'recordEarning' : ActorMethod<
    [Principal, bigint, EarningType, string, string],
    string
  >,
  'redeemFSU' : ActorMethod<[bigint, string], boolean>,
  'refundPledge' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<[string, string], string>,
  'rejectCrowdfundingCampaign' : ActorMethod<[string], boolean>,
  'removeTenantMember' : ActorMethod<[string, Principal], boolean>,
  'replyToThread' : ActorMethod<[bigint, string], bigint>,
  'resolveReferralCode' : ActorMethod<[string], [] | [Principal]>,
  'runPayCycle' : ActorMethod<[Principal], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCommissionRate' : ActorMethod<
    [MembershipTierLevel, bigint, EarningType, bigint, bigint],
    boolean
  >,
  'setCrowdfundingConfig' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'setMemberTier' : ActorMethod<[Principal, MembershipTierLevel], boolean>,
  'setPreferredLanguage' : ActorMethod<[string], undefined>,
  'suspendTenant' : ActorMethod<[string], boolean>,
  'unlinkWallet' : ActorMethod<[string], undefined>,
  'updateCampaign' : ActorMethod<
    [
      string,
      string,
      string,
      CampaignType,
      bigint,
      bigint,
      bigint,
      Array<string>,
    ],
    boolean
  >,
  'updateCrowdfundingCampaign' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'updateOrg' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    boolean
  >,
  'updateTenantBranding' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'upgradeMemberTier' : ActorMethod<[MembershipTierLevel], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];