/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingRecord {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'amountCents' : bigint,
  'tenantId' : string,
}
export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'title' : string,
  'endDate' : bigint,
  'orgId' : string,
  'goal' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'description' : string,
  'progress' : bigint,
  'supporterCount' : bigint,
  'campaignType' : CampaignType,
  'startDate' : bigint,
}
export type CampaignStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export type CampaignType = { 'action' : null } |
  { 'awareness' : null } |
  { 'fundraiser' : null } |
  { 'petition' : null };
export interface CommissionRate {
  'basisPoints' : bigint,
  'tier' : MembershipTierLevel,
  'flatAmountUnits' : bigint,
  'isActive' : boolean,
  'earningType' : EarningType,
  'depthLevel' : bigint,
}
export interface Credential {
  'id' : string,
  'status' : CredentialStatus,
  'title' : string,
  'expiresAt' : [] | [bigint],
  'subject' : Principal,
  'metadata' : string,
  'approvedAt' : [] | [bigint],
  'credentialType' : CredentialType,
  'description' : string,
  'updatedAt' : bigint,
  'isPublic' : boolean,
  'issuedAt' : bigint,
  'issuedBy' : Principal,
  'revokedAt' : [] | [bigint],
}
export type CredentialStatus = { 'active' : null } |
  { 'revoked' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type CredentialType = { 'verifiedHuman' : null } |
  { 'orgRepresentative' : null } |
  { 'eventAttendee' : null } |
  { 'expertiseBadge' : null } |
  { 'custom' : null } |
  { 'activistCertification' : null };
export interface CrowdfundingCampaign {
  'id' : string,
  'status' : CrowdfundingStatus,
  'coverImageUrl' : string,
  'title' : string,
  'creator' : Principal,
  'rewardTiers' : Array<CrowdfundingRewardTier>,
  'fundingModel' : CrowdfundingFundingModel,
  'approvedByAdmin' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'deadline' : bigint,
  'tenantId' : string,
  'goalCents' : bigint,
  'updatedAt' : bigint,
  'fsuContributionBps' : bigint,
  'backerCount' : bigint,
  'currency' : string,
  'totalFSUDistributed' : bigint,
  'category' : CrowdfundingCategory,
  'raisedCents' : bigint,
  'milestones' : Array<CrowdfundingMilestone>,
}
export type CrowdfundingCategory = { 'research' : null } |
  { 'civic' : null } |
  { 'education' : null } |
  { 'community' : null } |
  { 'crisisResponse' : null } |
  { 'humanitarian' : null } |
  { 'youth' : null };
export interface CrowdfundingConfig {
  'defaultFSUContributionBps' : bigint,
  'milestoneAchievementBonusBps' : bigint,
  'creatorFSUBonus' : bigint,
}
export type CrowdfundingFundingModel = { 'allOrNothing' : null } |
  { 'keepWhatYouRaise' : null };
export interface CrowdfundingMilestone {
  'id' : string,
  'title' : string,
  'achievedAt' : [] | [bigint],
  'bonusFSUAmount' : bigint,
  'description' : string,
  'targetCents' : bigint,
}
export interface CrowdfundingPledge {
  'id' : string,
  'status' : string,
  'referrerCode' : [] | [string],
  'receiptCode' : string,
  'createdAt' : bigint,
  'backer' : Principal,
  'campaignId' : string,
  'amountCents' : bigint,
  'rewardTierId' : [] | [string],
  'fsuEarned' : bigint,
}
export interface CrowdfundingRewardTier {
  'id' : string,
  'title' : string,
  'description' : string,
  'maxBackers' : [] | [bigint],
  'backerCount' : bigint,
  'minPledgeCents' : bigint,
}
export type CrowdfundingStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'funded' : null } |
  { 'failed' : null };
export interface DAOTokenRecord {
  'principal' : Principal,
  'balance' : bigint,
  'createdAt' : bigint,
  'totalEarned' : bigint,
  'totalBurned' : bigint,
  'lastAirdropAt' : [] | [bigint],
}
export interface DAOTokenTransaction {
  'id' : bigint,
  'to' : Principal,
  'from' : [] | [Principal],
  'note' : string,
  'createdAt' : bigint,
  'txType' : DAOTokenTxType,
  'amount' : bigint,
}
export type DAOTokenTxType = { 'votingReward' : null } |
  { 'transferred' : null } |
  { 'earned' : null } |
  { 'airdrop' : null } |
  { 'burned' : null };
export interface DebateComment {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'parentCommentId' : [] | [bigint],
  'createdAt' : bigint,
  'author' : Principal,
  'editedAt' : [] | [bigint],
  'proposalId' : bigint,
}
export interface DelegationRecord {
  'delegateTo' : Principal,
  'createdAt' : bigint,
  'isActive' : boolean,
  'delegator' : Principal,
  'proposalId' : [] | [bigint],
  'revokedAt' : [] | [bigint],
}
export interface DownlineMember {
  'principal' : Principal,
  'referralCode' : string,
  'joinedAt' : bigint,
  'tier' : MembershipTierLevel,
  'directReferralCount' : bigint,
}
export interface EarningRecord {
  'id' : string,
  'member' : Principal,
  'status' : EarningStatus,
  'createdAt' : bigint,
  'description' : string,
  'sourceId' : string,
  'earningType' : EarningType,
  'amountUnits' : bigint,
  'depthLevel' : bigint,
}
export type EarningStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'processing' : null };
export type EarningType = { 'eventCommission' : null } |
  { 'activityBonus' : null } |
  { 'directReferral' : null } |
  { 'levelOverride' : null } |
  { 'royaltyPool' : null } |
  { 'finFracFran' : null };
export interface EarningsSummary {
  'eventCommission' : bigint,
  'activityBonus' : bigint,
  'totalPaid' : bigint,
  'totalLifetime' : bigint,
  'directReferral' : bigint,
  'levelOverride' : bigint,
  'totalPending' : bigint,
  'royaltyPool' : bigint,
  'finFracFran' : bigint,
}
export interface FSUPoolStatus {
  'totalOutstandingFSU' : bigint,
  'valuePerUnitCents' : bigint,
  'poolSizeUnits' : bigint,
  'nextDistributionLabel' : string,
}
export interface FSURecord {
  'member' : Principal,
  'balance' : bigint,
  'lifetimeEarned' : bigint,
}
export interface FSUTransaction {
  'id' : string,
  'member' : Principal,
  'valuePerUnitCents' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'txType' : FSUTxType,
  'amount' : bigint,
}
export type FSUTxType = { 'redeemed' : null } |
  { 'transferred' : null } |
  { 'earned' : null };
export type ForumCategory = { 'resources' : null } |
  { 'general' : null } |
  { 'regional' : null } |
  { 'campaigns' : null } |
  { 'activism' : null } |
  { 'announcements' : null };
export interface ForumReply {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'isModeratorReply' : boolean,
  'threadId' : bigint,
}
export interface ForumThread {
  'id' : bigint,
  'status' : ThreadStatus,
  'title' : string,
  'orgId' : [] | [string],
  'body' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'viewCount' : bigint,
  'replyCount' : bigint,
  'category' : ForumCategory,
  'isPinned' : boolean,
}
export interface MemberTierRecord {
  'principal' : Principal,
  'referralCode' : string,
  'joinedAt' : bigint,
  'tier' : MembershipTierLevel,
  'upgradedAt' : bigint,
  'sponsorPrincipal' : [] | [Principal],
  'sponsorCode' : [] | [string],
}
export type MembershipTierLevel = { 'free' : null } |
  { 'founder' : null } |
  { 'executive' : null } |
  { 'affiliate' : null } |
  { 'ambassador' : null } |
  { 'partner' : null } |
  { 'associate' : null };
export interface Notification {
  'id' : string,
  'title' : string,
  'notifType' : NotificationType,
  'createdAt' : bigint,
  'recipient' : Principal,
  'isRead' : boolean,
  'message' : string,
}
export type NotificationType = { 'warning' : null } |
  { 'info' : null } |
  { 'credentialIssued' : null } |
  { 'error' : null } |
  { 'success' : null } |
  { 'credentialApproved' : null };
export interface OrgMember {
  'userId' : string,
  'joinedAt' : bigint,
  'role' : OrgMemberRole,
}
export type OrgMemberRole = { 'member' : null } |
  { 'admin' : null };
export type OrgStatus = { 'active' : null } |
  { 'archived' : null };
export interface Organization {
  'id' : string,
  'region' : string,
  'status' : OrgStatus,
  'members' : Array<OrgMember>,
  'orgType' : string,
  'foundedYear' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'website' : string,
}
export interface Proposal {
  'id' : bigint,
  'status' : ProposalStatus,
  'title' : string,
  'mechanism' : VotingMechanism,
  'enactedAt' : [] | [bigint],
  'orgId' : [] | [string],
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'quorumPercent' : bigint,
  'tenantId' : string,
  'proposalType' : ProposalType,
  'votingClosesAt' : [] | [bigint],
  'updatedAt' : bigint,
  'votingOpensAt' : [] | [bigint],
  'voteWindowHours' : bigint,
  'proposer' : Principal,
  'sponsors' : Array<Principal>,
  'sponsorThreshold' : bigint,
}
export type ProposalStatus = { 'review' : null } |
  { 'closed' : null } |
  { 'cancelled' : null } |
  { 'enacted' : null } |
  { 'rejected' : null } |
  { 'draft' : null } |
  { 'openVote' : null };
export type ProposalType = { 'resolution' : null } |
  { 'communityInitiative' : null } |
  { 'amendment' : null } |
  { 'budget' : null } |
  { 'policy' : null };
export interface RankedChoiceEntry { 'rank' : bigint, 'candidateId' : string }
export type Role = { 'member' : null } |
  { 'admin' : null } |
  { 'moderator' : null } |
  { 'guest' : null };
export interface RoyaltyPool {
  'id' : string,
  'isDistributed' : boolean,
  'period' : string,
  'createdAt' : bigint,
  'totalUnits' : bigint,
  'poolType' : RoyaltyPoolType,
}
export type RoyaltyPoolType = { 'event' : null } |
  { 'leadership' : null } |
  { 'global' : null } |
  { 'finFracFran' : null };
export interface Tenant {
  'id' : string,
  'status' : TenantStatus,
  'subscription' : [] | [TenantSubscription],
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'tier' : TenantTier,
  'storageUsedMb' : bigint,
  'updatedAt' : bigint,
  'branding' : [] | [TenantBranding],
  'trialEndsAt' : [] | [bigint],
}
export interface TenantBranding {
  'orgName' : string,
  'primaryColor' : string,
  'logoUrl' : string,
  'welcomeMessage' : string,
}
export interface TenantMember {
  'principal' : Principal,
  'role' : string,
  'tenantId' : string,
  'addedAt' : bigint,
}
export type TenantStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'suspended' : null };
export interface TenantSubscription {
  'monthlyCents' : bigint,
  'tier' : TenantTier,
  'renewalDate' : bigint,
  'startDate' : bigint,
}
export type TenantTier = { 'enterprise' : null } |
  { 'starter' : null } |
  { 'organization' : null };
export type ThreadStatus = { 'open' : null } |
  { 'locked' : null } |
  { 'archived' : null };
export interface Transaction {
  'id' : bigint,
  'description' : string,
  'walletAddress' : string,
  'timestamp' : bigint,
  'txType' : TransactionType,
  'amountICP' : number,
}
export type TransactionType = { 'sent' : null } |
  { 'received' : null };
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'id' : string,
  'bio' : string,
  'displayName' : string,
  'joinedAt' : bigint,
  'role' : Role,
  'isActive' : boolean,
  'avatarUrl' : string,
}
export interface Vote {
  'id' : bigint,
  'weight' : bigint,
  'voter' : Principal,
  'delegatedTo' : [] | [Principal],
  'castAt' : bigint,
  'choice' : VoteChoice,
  'proposalId' : bigint,
  'rankedChoices' : Array<RankedChoiceEntry>,
}
export type VoteChoice = { 'no' : null } |
  { 'yes' : null } |
  { 'abstain' : null };
export interface VoteTally {
  'noVotes' : bigint,
  'abstainWeight' : bigint,
  'yesWeight' : bigint,
  'totalVoters' : bigint,
  'mechanism' : VotingMechanism,
  'yesVotes' : bigint,
  'quorumPercent' : bigint,
  'totalVotesCast' : bigint,
  'rankedResults' : Array<[string, bigint]>,
  'quorumMet' : boolean,
  'tallyComputedAt' : bigint,
  'abstainVotes' : bigint,
  'noWeight' : bigint,
  'proposalId' : bigint,
  'passed' : boolean,
}
export type VotingMechanism = { 'simpleMajority' : null } |
  { 'liquidDelegation' : null } |
  { 'supermajority66' : null } |
  { 'supermajority75' : null } |
  { 'rankedChoice' : null };
export interface Wallet {
  'linkedAt' : bigint,
  'walletType' : WalletType,
  'address' : string,
  'balanceICP' : number,
  'walletLabel' : string,
}
export type WalletType = { 'internetIdentity' : null } |
  { 'plug' : null } |
  { 'stoic' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBillingRecord' : ActorMethod<[string, bigint, string, string], string>,
  'addDebateComment' : ActorMethod<
    [bigint, string, [] | [bigint]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addTenantMember' : ActorMethod<[string, Principal, string], boolean>,
  'addToFSUPool' : ActorMethod<[bigint, string], undefined>,
  'addToRoyaltyPool' : ActorMethod<[string, bigint], boolean>,
  'addTransaction' : ActorMethod<
    [string, number, string, TransactionType],
    undefined
  >,
  'adminListAllCrowdfundingCampaigns' : ActorMethod<
    [],
    Array<CrowdfundingCampaign>
  >,
  'adminListCrowdfundingPledges' : ActorMethod<
    [string],
    Array<CrowdfundingPledge>
  >,
  /**
   * / Admin-only. Distributes IIINTL tokens to all MLM-initialized members based on their tier.
   * / Sends a notification to each recipient.
   */
  'airdropToAllMembers' : ActorMethod<
    [],
    { 'totalTokens' : bigint, 'airdropped' : bigint }
  >,
  'approveCredential' : ActorMethod<[string], boolean>,
  'approveCrowdfundingCampaign' : ActorMethod<[string], boolean>,
  'archiveCampaign' : ActorMethod<[string], boolean>,
  'archiveOrg' : ActorMethod<[string], boolean>,
  'archiveThread' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Burns the caller's tokens. Reduces total supply. Awards 10 platform credits per token burned.
   */
  'burnDAOTokens' : ActorMethod<
    [bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'cancelProposal' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'cancelTenant' : ActorMethod<[string], boolean>,
  'castVote' : ActorMethod<
    [bigint, VoteChoice, Array<RankedChoiceEntry>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin-only. Iterates all tenants and suspends any that are in #trial
   * / status with a trialEndsAt timestamp that has already passed.
   * / Returns the count of tenants checked and the count expired.
   */
  'checkAndExpireTrials' : ActorMethod<
    [],
    { 'checked' : bigint, 'expired' : bigint }
  >,
  /**
   * / Awards 50 IIINTL voting reward tokens to a member who voted on a proposal.
   * / Prevents double-claiming per proposal per member.
   */
  'claimVotingReward' : ActorMethod<
    [bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'closeProposal' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createCampaign' : ActorMethod<
    [
      string,
      string,
      CampaignType,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
    ],
    string
  >,
  'createCrowdfundingCampaign' : ActorMethod<
    [
      string,
      string,
      CrowdfundingCategory,
      CrowdfundingFundingModel,
      bigint,
      string,
      bigint,
      string,
      Array<CrowdfundingRewardTier>,
      Array<CrowdfundingMilestone>,
      [] | [bigint],
    ],
    string
  >,
  'createOrg' : ActorMethod<
    [string, string, string, string, string, bigint],
    string
  >,
  'createProposal' : ActorMethod<
    [
      ProposalType,
      string,
      string,
      VotingMechanism,
      bigint,
      bigint,
      bigint,
      [] | [string],
      Array<string>,
    ],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createRoyaltyPool' : ActorMethod<[RoyaltyPoolType, string], string>,
  'createTenant' : ActorMethod<[string, TenantTier, [] | [bigint]], string>,
  'createThread' : ActorMethod<
    [string, string, ForumCategory, [] | [string], Array<string>],
    bigint
  >,
  'deactivateCommissionRate' : ActorMethod<
    [MembershipTierLevel, bigint, EarningType],
    boolean
  >,
  'delegateVote' : ActorMethod<
    [Principal, [] | [bigint]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'distributeFSU' : ActorMethod<[bigint, string], undefined>,
  'distributeRoyaltyPool' : ActorMethod<[string, bigint], boolean>,
  'editDebateComment' : ActorMethod<
    [bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'enactProposal' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'finalizeCrowdfundingCampaign' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[string], [] | [Campaign]>,
  'getCampaignPledges' : ActorMethod<[string], Array<CrowdfundingPledge>>,
  'getCampaignProgress' : ActorMethod<
    [string],
    [] | [{ 'goal' : bigint, 'progress' : bigint }]
  >,
  'getCampaignSupporterCount' : ActorMethod<[string], [] | [bigint]>,
  'getCommissionRate' : ActorMethod<
    [MembershipTierLevel, bigint, EarningType],
    [] | [CommissionRate]
  >,
  'getCommissionRates' : ActorMethod<[], Array<CommissionRate>>,
  'getCredential' : ActorMethod<[string], [] | [Credential]>,
  'getCrowdfundingCampaign' : ActorMethod<
    [string],
    [] | [CrowdfundingCampaign]
  >,
  'getCrowdfundingConfig' : ActorMethod<[], CrowdfundingConfig>,
  'getCrowdfundingPledge' : ActorMethod<[string], [] | [CrowdfundingPledge]>,
  /**
   * / Returns platform-wide DAO token statistics. Public, no auth required.
   */
  'getDAOTokenStats' : ActorMethod<
    [],
    {
      'treasuryBalance' : bigint,
      'totalHolders' : bigint,
      'totalSupply' : bigint,
    }
  >,
  /**
   * / Returns all DAO transactions where the caller is sender or recipient.
   */
  'getDAOTransactionHistory' : ActorMethod<[], Array<DAOTokenTransaction>>,
  /**
   * / Returns the top 20 token holders by balance. Public, no auth required.
   */
  'getDaoLeaderboard' : ActorMethod<[], Array<DAOTokenRecord>>,
  /**
   * / Returns all tenants whose trial will expire within the next `daysFromNow` days,
   * / including any that are already past their trial end date but not yet suspended.
   * / Sorted by trialEndsAt ascending (earliest expiry first).
   */
  'getExpiringTrials' : ActorMethod<[bigint], Array<Tenant>>,
  'getFSUPoolStatus' : ActorMethod<[], FSUPoolStatus>,
  'getLinkedWallets' : ActorMethod<[], Array<Wallet>>,
  'getMemberEarnings' : ActorMethod<[Principal], Array<EarningRecord>>,
  'getMemberTierRecord' : ActorMethod<[Principal], [] | [MemberTierRecord]>,
  'getMemberVote' : ActorMethod<[bigint, Principal], [] | [Vote]>,
  'getMyCredentials' : ActorMethod<[], Array<Credential>>,
  /**
   * / Returns the caller's DAO token record. Returns a zero-balance record if not yet initialized.
   */
  'getMyDAOBalance' : ActorMethod<[], DAOTokenRecord>,
  'getMyDelegation' : ActorMethod<[], [] | [DelegationRecord]>,
  'getMyDownline' : ActorMethod<[], Array<DownlineMember>>,
  'getMyEarnings' : ActorMethod<[], Array<EarningRecord>>,
  'getMyEarningsSummary' : ActorMethod<[], EarningsSummary>,
  'getMyFSURecord' : ActorMethod<[], [] | [FSURecord]>,
  'getMyFSUTransactions' : ActorMethod<[], Array<FSUTransaction>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyPledges' : ActorMethod<[], Array<CrowdfundingPledge>>,
  'getMyReferralCode' : ActorMethod<[], [] | [string]>,
  'getMyRoyaltyDistributions' : ActorMethod<[], Array<EarningRecord>>,
  'getMyTenant' : ActorMethod<[], [] | [Tenant]>,
  'getMyTierRecord' : ActorMethod<[], [] | [MemberTierRecord]>,
  'getMyUplineChain' : ActorMethod<[], Array<MemberTierRecord>>,
  'getOrg' : ActorMethod<[string], [] | [Organization]>,
  'getOrgMembers' : ActorMethod<[string], Array<OrgMember>>,
  'getPreferredLanguage' : ActorMethod<[], string>,
  'getProposal' : ActorMethod<[bigint], [] | [Proposal]>,
  'getProposalComments' : ActorMethod<[bigint], Array<DebateComment>>,
  /**
   * / Returns all debate comments for a proposal.
   * / No authentication required.
   */
  'getProposalCommentsPublic' : ActorMethod<[bigint], Array<DebateComment>>,
  /**
   * / Returns a single proposal by ID if it is not in draft or cancelled state.
   * / No authentication required.
   */
  'getProposalPublic' : ActorMethod<[bigint], [] | [Proposal]>,
  'getProposalSponsors' : ActorMethod<[bigint], Array<Principal>>,
  'getQuorumStatus' : ActorMethod<
    [bigint],
    {
      'totalVoters' : bigint,
      'quorumPercent' : bigint,
      'percentVoted' : bigint,
      'quorumMet' : boolean,
      'votesCast' : bigint,
    }
  >,
  'getReplies' : ActorMethod<[bigint], Array<ForumReply>>,
  'getRoyaltyPool' : ActorMethod<[string], [] | [RoyaltyPool]>,
  'getTenant' : ActorMethod<[string], [] | [Tenant]>,
  'getTenantBranding' : ActorMethod<[string], [] | [TenantBranding]>,
  'getThread' : ActorMethod<[bigint], [] | [ForumThread]>,
  'getTransactionHistory' : ActorMethod<[[] | [string]], Array<Transaction>>,
  /**
   * / Returns the timestamp of the last heartbeat expiry check and
   * / a human-readable string showing how long until the next check fires.
   */
  'getTrialAutomationStatus' : ActorMethod<
    [],
    { 'lastCheck' : bigint, 'nextCheckIn' : string }
  >,
  'getUserOrgs' : ActorMethod<[string], Array<Organization>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteTally' : ActorMethod<[bigint], [] | [VoteTally]>,
  /**
   * / Returns the current vote tally for a proposal.
   * / No authentication required.
   */
  'getVoteTallyPublic' : ActorMethod<[bigint], [] | [VoteTally]>,
  'getVotesByProposal' : ActorMethod<[bigint], Array<Vote>>,
  'getWalletBalance' : ActorMethod<[string], number>,
  'incrementThreadView' : ActorMethod<[bigint], boolean>,
  'initMemberMLM' : ActorMethod<[[] | [string]], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueCredential' : ActorMethod<
    [Principal, CredentialType, string, string, string, [] | [bigint]],
    string
  >,
  'joinCampaign' : ActorMethod<[string], boolean>,
  'joinOrg' : ActorMethod<[string], boolean>,
  'leaveCampaign' : ActorMethod<[string], boolean>,
  'leaveOrg' : ActorMethod<[string], boolean>,
  'linkWallet' : ActorMethod<[WalletType, string, string], undefined>,
  'listActiveCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listActiveOrgs' : ActorMethod<[], Array<Organization>>,
  'listActiveProposals' : ActorMethod<[], Array<Proposal>>,
  'listAllCredentialsAdmin' : ActorMethod<[], Array<Credential>>,
  /**
   * / Admin-only. Returns all DAO token records for admin oversight.
   */
  'listAllDAOTokensAdmin' : ActorMethod<[], Array<DAOTokenRecord>>,
  'listAllMemberTiers' : ActorMethod<[], Array<MemberTierRecord>>,
  'listBillingHistory' : ActorMethod<[string], Array<BillingRecord>>,
  'listCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listCampaignsByOrg' : ActorMethod<[string], Array<Campaign>>,
  'listCrowdfundingCampaigns' : ActorMethod<[], Array<CrowdfundingCampaign>>,
  'listCrowdfundingCampaignsByCategory' : ActorMethod<
    [CrowdfundingCategory],
    Array<CrowdfundingCampaign>
  >,
  'listMyCrowdfundingCampaigns' : ActorMethod<[], Array<CrowdfundingCampaign>>,
  'listOrgs' : ActorMethod<[], Array<Organization>>,
  'listProposals' : ActorMethod<[], Array<Proposal>>,
  'listProposalsByStatus' : ActorMethod<[ProposalStatus], Array<Proposal>>,
  'listProposalsByType' : ActorMethod<[ProposalType], Array<Proposal>>,
  /**
   * / Returns all non-draft, non-cancelled proposals visible to the public feed.
   * / No authentication required.
   */
  'listProposalsPublic' : ActorMethod<[], Array<Proposal>>,
  'listPublicCredentialsByType' : ActorMethod<
    [CredentialType],
    Array<Credential>
  >,
  'listRoyaltyPools' : ActorMethod<[], Array<RoyaltyPool>>,
  'listTenantMembers' : ActorMethod<[string], Array<TenantMember>>,
  'listTenants' : ActorMethod<[], Array<Tenant>>,
  'listThreads' : ActorMethod<[], Array<ForumThread>>,
  'listThreadsByCategory' : ActorMethod<[ForumCategory], Array<ForumThread>>,
  'listThreadsByOrg' : ActorMethod<[string], Array<ForumThread>>,
  'listUsers' : ActorMethod<[], Array<UserSummary>>,
  'lockThread' : ActorMethod<[bigint], boolean>,
  'markEarningPaid' : ActorMethod<[string], boolean>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'openProposalForVoting' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'pinThread' : ActorMethod<[bigint], boolean>,
  'pledgeToCrowdfundingCampaign' : ActorMethod<
    [string, bigint, [] | [string], [] | [string]],
    string
  >,
  'processReferralChainBonus' : ActorMethod<
    [Principal, bigint, EarningType, string],
    undefined
  >,
  'reactivateTenant' : ActorMethod<[string], boolean>,
  'recordEarning' : ActorMethod<
    [Principal, bigint, EarningType, string, string],
    string
  >,
  'redeemFSU' : ActorMethod<[bigint, string], boolean>,
  'refundPledge' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<[string, string], string>,
  'rejectCredential' : ActorMethod<[string], boolean>,
  'rejectCrowdfundingCampaign' : ActorMethod<[string], boolean>,
  'removeTenantMember' : ActorMethod<[string, Principal], boolean>,
  'replyToThread' : ActorMethod<[bigint, string], bigint>,
  'resolveReferralCode' : ActorMethod<[string], [] | [Principal]>,
  'revokeCredential' : ActorMethod<[string], boolean>,
  'revokeDelegation' : ActorMethod<
    [[] | [bigint]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'runPayCycle' : ActorMethod<[Principal], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Sends in-platform notifications to tenant owners based on days remaining
   * / in their trial (7, 3, 1 days) and for already-expired trials.
   * / Returns a summary of how many notifications were sent.
   */
  'sendTrialExpiryNotifications' : ActorMethod<[], string>,
  'setCommissionRate' : ActorMethod<
    [MembershipTierLevel, bigint, EarningType, bigint, bigint],
    boolean
  >,
  'setCrowdfundingConfig' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'setMemberTier' : ActorMethod<[Principal, MembershipTierLevel], boolean>,
  'setPreferredLanguage' : ActorMethod<[string], undefined>,
  'sponsorProposal' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'suspendTenant' : ActorMethod<[string], boolean>,
  'toggleCredentialPublic' : ActorMethod<[string, boolean], boolean>,
  /**
   * / Peer-to-peer token transfer between members.
   */
  'transferDAOTokens' : ActorMethod<
    [Principal, bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'unlinkWallet' : ActorMethod<[string], undefined>,
  'updateCampaign' : ActorMethod<
    [
      string,
      string,
      string,
      CampaignType,
      bigint,
      bigint,
      bigint,
      Array<string>,
    ],
    boolean
  >,
  'updateCrowdfundingCampaign' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'updateOrg' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    boolean
  >,
  'updateTenantBranding' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'upgradeMemberTier' : ActorMethod<[MembershipTierLevel], boolean>,
  'withdrawSponsor' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];